### PR TITLE
Add Gels to lapack64 interface in preparation for fixing mat64.Solve

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
I kept the full comment because Gels is tricky in a number of ways.

**Comment by btracey** [comment]
@kortschak The test is failing because I forgot to add the cgo functionality. I went to add it, but it turns out that the function signature in the c header is not the same as the native/Fortran function interface. There is no work or lwork. I took a guess at what I thought was reasonable functionality.

**Comment by btracey** [comment]
This is failing on 1.5beta2 because of golang/go/issue/11738. The go issue has been fixed.

**Comment by kortschak** [comment]
Rebase this onto master.

**Comment by btracey** [comment]
This functionality has been otherwise merged.

**Comment by btracey** [comment]
PTAL @kortschak

**Pull request closed without merging**
