### PR TITLE
native: avoid allocation in Dormlq

### PR DESCRIPTION
**Pull request by vladimir-ch**
@btracey @kortschak PTAL

### CODE REVIEW

**Comment by kortschak** [comment]
Is it worth sending the equivalent change to LAPACK?

**Comment by vladimir-ch** [comment]
No, this is just what the reference is doing.

**Comment by kortschak** [comment]
I completely missed that. When I had a look I went [here](ftp://ftp2.uk.freebsd.org/sites/ftp.netlib.org/lapack/explore-html/de/dff/dormlq_8f_source.html) instead of NETLIB (I have no idea why). It is at 3.4.2 instead of 3.7.0 and uses a temporary, `t( ldt, nbmax )`.

**Comment by vladimir-ch** [comment]
Ah, now I understand where the previous code was coming from.

**Pull request merged**
