### PR TITLE
go 1.7beta1 -> go 1.7beta2

### PR DESCRIPTION
**Pull request by jonlawlor**

### CODE REVIEW

**Comment by sbinet** [comment]
hum... it fails https://travis-ci.org/gonum/lapack/jobs/138444863#L505
(but this seems to be a pre-existing condition)

LGTM

**Comment by jonlawlor** [comment]
Yes, I think that error already exists, because all of the versions are failing.

**Comment by kortschak** [comment]
#149?

**Comment by jonlawlor** [comment]
Looks like it.

**Pull request merged**
