### PR TITLE
Add Dlacpy and tests

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
@kortschak , this has three options for uplo. blas.Upper, blas.Lower, and blas.All. I'm not sure what the correct fix to the generator is (nor how special case this function is).

**Comment by kortschak** [comment]
#58 should fix that.

**Comment by btracey** [comment]
Thanks.

**Comment by kortschak** [comment]
This gives me an understanding of why the assembler does know all the instruction sets.

**Comment by btracey** [comment]
Do you mean doesn't?

**Comment by kortschak** [comment]
Indeed I do.

**Comment by kortschak** [comment]
LGTM after rebase onto master and cgo tests pass.

**Pull request merged**
