### PR TITLE
Adddlansy

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
This is needed for Dpocon and is also another independent implementation that matches Dlange.

**Comment by kortschak** [comment]
LGTM

**Comment by btracey** [comment]
This is getting errors like "The command "git checkout -qf aef0c79470553a2914507a575c007dcaf2ec46ef" failed and exited with 128 during ." Does that mean anything to you @kortschak  @jonlawlor ?

**Comment by kortschak** [comment]
Via travis? Travis has been very sluggish today.

**Comment by btracey** [comment]
Yea, it's been extremely slow. It gave the message once and I restarted it, and it failed again with the same message.

**Comment by kortschak** [comment]
I ran the tests on my laptop before the LGTM, so I'm happy to have it merged now if you are.

**Comment by btracey** [comment]
Alright. If this is still freaking out when I can get to implementing Dpocon then I'll merge.

If you have a minute, could you look at the Dgecon PR? I'd like to test Dtrcon and Dpocon against Dgecon to increase confidence in correctness.

**Pull request merged**
