### PR TITLE
cgo: enable tests for Dormbr and Dormlq

### LINKED ISSUE #241: cgo: tests for Dormbr and Dormlq comments though fixes in OpenBLAS merged
This is a complicated issue. The tests for Dormbr and Dormlq are commented out with reference to OpenBLAS issues and PRs. The issues have been closed and the PRs have been merged. This would suggest that these tests could and should be uncommented. I have just tried that, and they fail.

```
$ CGO_LDFLAGS="-L/usr/local -lopenblas" go test -run Dormlq
*** Error in `/tmp/go-build141511666/github.com/gonum/lapack/cgo/_test/cgo.test': free(): invalid next size (fast): 0x00000000028bb7b0 ***
[more]
```
```
$ CGO_LDFLAGS="-L/usr/local -lopenblas" go test -run Dormbr
 ** On entry to DORMBRP parameter number 13 had an illegal value
[more]
```

### PR DESCRIPTION
**Pull request by vladimir-ch**
LAPACKE bugs have been now fixed both in Reference LAPACK and in OpenBLAS.

I will wait for Travis to finish before merging.

Fixes #241

### CODE REVIEW

**Comment by kortschak** [comment]
The failure on travis is reflected on my machine as well.

**Comment by vladimir-ch** [comment]
Do you get some error messages from LAPACK itself? I can't check right now.

**Comment by kortschak** [comment]
Yes, parameter 13.

**Comment by vladimir-ch** [comment]
Ok, that's on our side, bad work slice. I'll fix it later.

**Comment by btracey** [comment]
LGTM

**Comment by kortschak** [comment]
LGTM

**Pull request merged**
