### PR TITLE
Revert "Adddsyev"

### PR DESCRIPTION
**Pull request by btracey**
Reverts gonum/lapack#108

### CODE REVIEW

**Comment by btracey** [comment]
I have no idea what happened. Working on it.

**Comment by kortschak** [comment]
What was this for?

**Comment by btracey** [comment]
The PR got messed up somehow and all the Dsyev code was deleted. I have no idea how I did that. I'm sorry.

**Comment by kortschak** [comment]
I'm not completely surprised. The pattern of 

```
a->b->c
      `->d
```

where both c and d are the subjects of pull requests are fraught if not done carefully.

**Comment by btracey** [comment]
Apparently! I have the testing code saved, and the first half of the function exists in the github history. Reconstructing the rest now.

**Comment by kortschak** [comment]
My suggestion for the future is to either work linearly and accept delay or work atomically and have both requirements merge in the same PR. Linear history is a good thing.

**Pull request merged**
