### PR TITLE
Add dlacn2

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
This function is very iterative and so hard to test directly, and there's no cgo function to compare to. However, when this is merged along with the other two current PRs, they will all be called by Dgecon which we can test against cgo.

**Comment by kortschak** [comment]
Ugh, that fortran spaghetti is horrible.

LGTM

**Comment by btracey** [comment]
Yep. The original FORTRAN was worse.

**Comment by kortschak** [comment]
I meant the NETLIB 3.5 code - yours is good.

**Comment by kortschak** [comment]
Oops, isave should be a *[3]int or be returned, the mutations you are doing are not visible externally. Sorry I missed that.

**Pull request merged**
